[control_plane]
k8s-control-plane ansible_host=54.226.120.81

[workers]
k8s-worker-1 ansible_host=98.93.49.46
k8s-worker-2 ansible_host=32.197.240.195

[k8s_cluster:children]
control_plane
workers

[k8s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/k8s-lab
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
