[control_plane]
k8s-control-plane ansible_host=44.199.213.16

[workers]
k8s-worker-1 ansible_host=32.199.197.252
k8s-worker-2 ansible_host=32.197.187.64

[k8s_cluster:children]
control_plane
workers

[k8s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/k8s-lab
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
