---
- name: Preparar todos os nós do cluster
  hosts: k8s_cluster
  become: true

  roles:
    - common
    - containerd
    - kubernetes

- name: Inicializar o Control Plane e instalar o Calico
  hosts: control_plane
  become: true

  roles:
    - control-plane
